[package]
name = "zed_swift"
version = "0.3.1"
edition = "2021"
publish = false

[lib]
path = "src/swift.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.116"
zed_extension_api = "0.0.6"
